#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MPI applications on 
# TACC's Stampede system.
#
#----------------------------------------------------

#SBATCH -J q2           # Job name
#SBATCH -o q2.%j.out       # Name of stdout output file (%j expands to jobId)
#SBATCH -p normal        # Queue name
#SBATCH -N 256                  # Total number of nodes requested (16 cores/node)
#SBATCH -n 4096                 # Total number of mpi tasks requested
#SBATCH -t 00:30:00           # Run time (hh:mm:ss) - 1.5 hours

#SBATCH -A TG-ASC170005      # <-- Allocation name to charge job against

# Launch the MPI executable named "a.out"

NL=100
ITER=1000
NSTRONG=6400
array=(1 4 16 64 256 1024 4096)
for i in "${array[@]}"
do
        sq=$(echo -e "sqrt($i)\nquit\n" | bc -q -i | head -2 | tail -1)
        ibrun -o 0 -n $i ./jacobi-mpi2D $((sq*NL)) $ITER
done

for i in "${array[@]}"
do
        sq=$(echo -e "sqrt($i)\nquit\n" | bc -q -i | head -2 | tail -1)
        ibrun -o 0 -n $i ./jacobi-mpi2D-nonBlocking $((sq*NL)) $ITER
done

for i in "${array[@]}"
do
        ibrun -o 0 -n $i ./jacobi-mpi2D $NSTRONG $ITER
done

for i in "${array[@]}"
do
        ibrun -o 0 -n $i ./jacobi-mpi2D-nonBlocking $NSTRONG $ITER
done