#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MPI applications on 
# TACC's Stampede system.
#
#----------------------------------------------------

#SBATCH -J q3           # Job name
#SBATCH -o q3.%j.out       # Name of stdout output file (%j expands to jobId)
#SBATCH -p development        # Queue name
#SBATCH -N 4                  # Total number of nodes requested (16 cores/node)
#SBATCH -n 64                 # Total number of mpi tasks requested
#SBATCH -t 00:30:00           # Run time (hh:mm:ss) - 1.5 hours

#SBATCH -A TG-ASC170005      # <-- Allocation name to charge job against

# Launch the MPI executable named "a.out"

mkdir $SLURM_JOB_ID
cd $SLURM_JOB_ID
array=( 100 1000 5000 10000 50000 100000 500000 1000000 5000000 10000000)
for i in "${array[@]}"
do
	ibrun ./ssort $i
	python ./test.py 64
	rm output*
done